import './globals.css'
import { Inter } from 'next/font/google'
import Nav from '../app/(components)/Nav';

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';

config.autoAddCss = false;

// rest of the code...

const inter = Inter({ subsets: ['latin'] })
export const metadata = {
  title: 'TIcket App',
  description: 'Generated by Harshsukhija',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <div className="flex flex-col h-screen max-h-screen">
      <Nav/>
      <div className='flex-grow overfole-y-auto bg-page text-default-text'>
      {children}
      </div>
      </div>
      </body>
    </html>
  )
}
